baseURL = 'https://aptc.io'
languageCode = 'en-us'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/posts"

[params]
author = "Chuck"
user = "chuck"
hostname = "aptc.io"

readingTime = false  # Show reading time on post page
published = false  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/chucksploit"

[[params.social]]
key = 1
name = "twitter"
url = "https://www.twitter.com/chucksploit"