baseURL = 'https://aptc.io'
languageCode = 'en-us'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/posts"

[params]
author = "chucksploit"
user = "chucksploit"
hostname = "aptc.io"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/chucksploit"

[[params.social]]
key = 1
name = "twitter"
url = "https://www.twitter.com/chucksploit"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/chucksploit"